name: Testes Automatizados

# Quando esse robô deve acordar?
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# O que ele deve fazer?
jobs:
  build:
    runs-on: ubuntu-latest # Ele vai usar uma máquina Linux virtual

    steps:
    # 1. Baixar o seu código
    - name: Checkout do código
      uses: actions/checkout@v4

    # 2. Instalar o Python
    - name: Configurar Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    # 3. Instalar as dependências (pytest, requests, etc.)
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Rodar os testes
    - name: Rodar Testes com Pytest
      run: |
        pytest -v